# Generated by Django 3.2.25 on 2024-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myenvapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('age', models.BigIntegerField()),
            ],
        ),
    ]
