# Generated by Django 3.2.25 on 2024-04-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myenvapp', '0006_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageTest',
        ),
    ]
